@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.alcatrazescapee.notreepunching.client.particle;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;